### ISSUE TITLE
timbre unavailable in clojurescript

### ISSUE THREAD

**Issue by lvh** [ptaoussanis/timbre#101]
Using timbre: `[com.taoensso/timbre "4.0.0-beta4"]` and Clojurescript: `[org.clojure/clojurescript "0.0-3269" :scope "provided"]`.

I'm working on a reproduction terminal session.

**Comment by lvh** [comment]
```
➜  shrieker git:(master) ✗ lein clean                                                                                                                                     08:51:27
➜  shrieker git:(master) ✗ fgrep timbre project.clj                                                                                                                       08:51:37
                 [com.taoensso/timbre "3.4.0"]]
➜  shrieker git:(master) ✗ lein repl                                                                                                                                      08:51:39
nREPL server started on port 51051 on host 127.0.0.1 - nrepl://127.0.0.1:51051
REPL-y 0.3.5, nREPL 0.2.10
Clojure 1.7.0-beta3
Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-b25
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e
shrieker.repl=> (ns my-app (:require [taoensso.timbre :refer [log]]))
nil
my-app=> Bye for now!
➜  shrieker git:(master) ✗ lein clean                                                                                                                                     08:53:55
➜  shrieker git:(master) ✗ fgrep timbre project.clj                                                                                                                       08:54:13
                 [com.taoensso/timbre "4.0.0-beta4"]]
➜  shrieker git:(master) ✗ lein repl                                                                                                                                      08:54:16
nREPL server started on port 51159 on host 127.0.0.1 - nrepl://127.0.0.1:51159
REPL-y 0.3.5, nREPL 0.2.10
Clojure 1.7.0-beta3
Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-b25
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

shrieker.repl=> (ns my-app (:require [taoensso.timbre :refer [log]]))
nil
my-app=> Bye for now!
➜  shrieker git:(master) ✗ lein do figwheel                                                                                                                               08:55:41
Figwheel: Starting server at http://localhost:3449
Focusing on build ids: app
Compiling "resources/public/js/app.js" from ["src/cljs" "env/dev/cljs" "test/cljs"]...
WARNING: Use of undeclared Var shrieker.core/spy at line 84 src/cljs/shrieker/core.cljs
Successfully compiled "resources/public/js/app.js" in 7.149 seconds.
Started Figwheel autobuilder

Launching ClojureScript REPL for build: app
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (fig-status)                    ;; displays current state of system
          (add-dep [org.om/om "0.8.1"]) ;; add a dependency. very experimental
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when figwheel connects to your application
To quit, type: :cljs/quit
cljs.user=> (ns my-app (:require [taoensso.timbre :refer [log]]))
WARNING: my-app is a single segment namespace at line 1 <cljs repl>
clojure.lang.ExceptionInfo: Referred var taoensso.timbre/log does not exist at line 1 <cljs repl> {:file "<cljs repl>", :line 1, :column 1, :tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4591)
	at cljs.analyzer$error.invoke(analyzer.cljc:384)
	at cljs.analyzer$error.invoke(analyzer.cljc:382)
	at cljs.analyzer$check_uses.invoke(analyzer.cljc:1300)
	at cljs.analyzer$eval1872$fn__1874.invoke(analyzer.cljc:1547)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:1900)
	at cljs.analyzer$analyze$fn__2122.invoke(analyzer.cljc:1992)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:1985)
	at cljs.repl$evaluate_form.invoke(repl.cljc:429)
	at cljs.repl$eval_cljs.invoke(repl.cljc:547)
	at cljs.repl$repl_STAR_$read_eval_print__4303.invoke(repl.cljc:814)
	at cljs.repl$repl_STAR_$fn__4309$fn__4316.invoke(repl.cljc:851)
	at cljs.repl$repl_STAR_$fn__4309.invoke(repl.cljc:850)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:968)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:816)
	at figwheel_sidecar.repl$repl.invoke(repl.clj:173)
	at figwheel_sidecar.repl$start_repl.invoke(repl.clj:472)
	at figwheel_sidecar.repl$cljs_repl.invoke(repl.clj:488)
	at figwheel_sidecar.repl$repl_switching_loop.invoke(repl.clj:498)
	at figwheel_sidecar.repl$repl_switching_loop.invoke(repl.clj:495)
	at figwheel_sidecar.repl$run_autobuilder.invoke(repl.clj:539)
	at user$eval22071.invoke(form-init8602785585825003877.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6792)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.load(Compiler.java:7237)
	at clojure.lang.Compiler.loadFile(Compiler.java:7175)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

Is there a different way to import it I'm not aware of? Really looking forward to using timbre in cljs :)

**Comment by ptaoussanis** [comment]
Hi Laurens, first thing I'd check  - `log` is a macro, not a function. The correct way to require Timbre in Cljs is:

```clojure
(:require [taoensso.timbre :as timbre :refer-macros ; Note :refer-macros, not :refer
  (log  trace  debug  info  warn  error  fatal  report
   logf tracef debugf infof warnf errorf fatalf reportf
   spy)])
```

Just realised the README doesn't point this out, I'll update shortly.

If you're still having trouble after that, I'd suggest trying to confirm that Figwheel is configured to support .cljx files correctly (I'm not familiar with Figwheel myself, sorry).

Let me know if that helps?

Cheers! :-)

**Comment by ptaoussanis** [comment]
Have updated the README docs btw: https://github.com/ptaoussanis/timbre#dependencies

Thanks for bringing this to my attention.

**Comment by lvh** [comment]
Oh, derp! Somewhere in the back of my head I knew that was the case, but... I'll try that soon :)

**Comment by ptaoussanis** [comment]
No derp necessary, the docs were wrong :-)

**Comment by ptaoussanis** [comment]
Closing this for now, please feel free to reopen if you're still having any issues.
