### ISSUE TITLE
clojure.lang.Var$Unbound cannot be cast to clojure.lang.MultiFn when using timbre

### ISSUE THREAD

**Issue by vadali** [ptaoussanis/timbre#203]
Hi,
I am using timbre for a bunch of my projects, and recently I get this error message when trying to start the repl using lein (and aot-ing the namespace):

```
Compiling my.namespace
java.lang.ExceptionInInitializerError, compiling:(namespace.clj:1:1)
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(namespace.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler.compile1(Compiler.java:7474)
	at clojure.lang.Compiler.compile1(Compiler.java:7464)
	at clojure.lang.Compiler.compile(Compiler.java:7541)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$compile$fn__5682.invoke(core.clj:5903)
	at clojure.core$compile.invokeStatic(core.clj:5903)
	at clojure.core$compile.invoke(core.clj:5895)
	at user$eval20$fn__29.invoke(form-init861878461596598091.clj:1)
	at user$eval20.invokeStatic(form-init861878461596598091.clj:1)
	at user$eval20.invoke(form-init861878461596598091.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at taoensso.timbre$loading__5569__auto____1909.invoke(timbre.clj:1)
	at taoensso.timbre__init.load(Unknown Source)
	at taoensso.timbre__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at my.namespace$loading__5569__auto____36.invoke(namespace.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	... 35 more
Caused by: java.lang.ClassCastException: clojure.lang.Var$Unbound cannot be cast to clojure.lang.MultiFn
	at clojure.core$methods.invokeStatic(core.clj:1719)
	at clojure.core$methods.invoke(core.clj:1719)
	at io.aviso.exception$fn__2157.invokeStatic(exception.clj:480)
	at io.aviso.exception$fn__2157.invoke(exception.clj:478)
	at io.aviso.exception__init.load(Unknown Source)
	at io.aviso.exception__init.<clinit>(Unknown Source)
	... 92 more
Compilation failed: Subprocess failed

```

If I do `lein clean` and `lein repl` it works once, but then stops again, forcing me to effectively do `lein clean` every time.. If I remove all dependencies of `timbre` everything works fine again.. 

Did anyone encounter this problem before? any tips? 

Thanks!

**Comment by vadali** [comment]
Ok, so looking all over the place, I tried to see what upgrading clojure for this project does, and it gave some more insights:

(error now moved from line 1 to line 19 because I moved the `(require '[taoensso.timbre])` to its own line, 19)

> Compiling my.namespace
> WARNING: pos-int? already refers to: #'clojure.core/pos-int? in namespace: taoensso.encore, being replaced by: #'taoensso.encore/pos-int?
> java.lang.ExceptionInInitializerError, compiling:(namespace.clj:19:1)
> Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(namespace.clj:19:1)
> 	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
> 	at clojure.lang.Compiler.compile1(Compiler.java:7525)
> 	at clojure.lang.Compiler.compile(Compiler.java:7592)
> 	at clojure.lang.RT.compile(RT.java:408)
> 	at clojure.lang.RT.load(RT.java:453)
> 	at clojure.lang.RT.load(RT.java:421)
> 	at clojure.core$load$fn__7846.invoke(core.clj:6008)
> 	at clojure.core$load.invokeStatic(core.clj:6007)
> 	at clojure.core$load.doInvoke(core.clj:5991)
> 	at clojure.lang.RestFn.invoke(RestFn.java:408)
> 	at clojure.core$load_one.invokeStatic(core.clj:5812)
> 	at clojure.core$compile$fn__7851.invoke(core.clj:6018)
> 	at clojure.core$compile.invokeStatic(core.clj:6018)
> 	at clojure.core$compile.invoke(core.clj:6010)
> 	at user$eval30$fn__39.invoke(form-init7463519023984998664.clj:1)
> 	at user$eval30.invokeStatic(form-init7463519023984998664.clj:1)
> 	at user$eval30.invoke(form-init7463519023984998664.clj:1)
> 	at clojure.lang.Compiler.eval(Compiler.java:6978)
> 	at clojure.lang.Compiler.eval(Compiler.java:6968)
> 	at clojure.lang.Compiler.eval(Compiler.java:6968)
> 	at clojure.lang.Compiler.load(Compiler.java:7430)
> 	at clojure.lang.Compiler.loadFile(Compiler.java:7368)
> 	at clojure.main$load_script.invokeStatic(main.clj:277)
> 	at clojure.main$init_opt.invokeStatic(main.clj:279)
> 	at clojure.main$init_opt.invoke(main.clj:279)
> 	at clojure.main$initialize.invokeStatic(main.clj:310)
> 	at clojure.main$null_opt.invokeStatic(main.clj:344)
> 	at clojure.main$null_opt.invoke(main.clj:341)
> 	at clojure.main$main.invokeStatic(main.clj:423)
> 	at clojure.main$main.doInvoke(main.clj:386)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 	at clojure.lang.Var.applyTo(Var.java:700)
> 	at clojure.main.main(main.java:37)
> Caused by: java.lang.ExceptionInInitializerError
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at clojure.lang.RT.classForName(RT.java:2183)
> 	at clojure.lang.RT.classForName(RT.java:2192)
> 	at clojure.lang.RT.loadClassForName(RT.java:2211)
> 	at clojure.lang.RT.load(RT.java:445)
> 	at clojure.lang.RT.load(RT.java:421)
> 	at clojure.core$load$fn__7846.invoke(core.clj:6008)
> 	at clojure.core$load.invokeStatic(core.clj:6007)
> 	at clojure.core$load.doInvoke(core.clj:5991)
> 	at clojure.lang.RestFn.invoke(RestFn.java:408)
> 	at clojure.core$load_one.invokeStatic(core.clj:5812)
> 	at clojure.core$load_one.invoke(core.clj:5807)
> 	at clojure.core$load_lib$fn__7791.invoke(core.clj:5852)
> 	at clojure.core$load_lib.invokeStatic(core.clj:5851)
> 	at clojure.core$load_lib.doInvoke(core.clj:5832)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:142)
> 	at clojure.core$apply.invokeStatic(core.clj:659)
> 	at clojure.core$load_libs.invokeStatic(core.clj:5889)
> 	at clojure.core$load_libs.doInvoke(core.clj:5873)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 	at clojure.core$apply.invokeStatic(core.clj:659)
> 	at clojure.core$require.invokeStatic(core.clj:5911)
> 	at clojure.core$require.doInvoke(core.clj:5911)
> 	at clojure.lang.RestFn.invoke(RestFn.java:457)
> 	at taoensso.timbre$loading__5569__auto____1909.invoke(timbre.clj:1)
> 	at taoensso.timbre__init.load(Unknown Source)
> 	at taoensso.timbre__init.<clinit>(Unknown Source)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at clojure.lang.RT.classForName(RT.java:2183)
> 	at clojure.lang.RT.classForName(RT.java:2192)
> 	at clojure.lang.RT.loadClassForName(RT.java:2211)
> 	at clojure.lang.RT.load(RT.java:445)
> 	at clojure.lang.RT.load(RT.java:421)
> 	at clojure.core$load$fn__7846.invoke(core.clj:6008)
> 	at clojure.core$load.invokeStatic(core.clj:6007)
> 	at clojure.core$load.doInvoke(core.clj:5991)
> 	at clojure.lang.RestFn.invoke(RestFn.java:408)
> 	at clojure.core$load_one.invokeStatic(core.clj:5812)
> 	at clojure.core$load_one.invoke(core.clj:5807)
> 	at clojure.core$load_lib$fn__7791.invoke(core.clj:5852)
> 	at clojure.core$load_lib.invokeStatic(core.clj:5851)
> 	at clojure.core$load_lib.doInvoke(core.clj:5832)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:142)
> 	at clojure.core$apply.invokeStatic(core.clj:659)
> 	at clojure.core$load_libs.invokeStatic(core.clj:5889)
> 	at clojure.core$load_libs.doInvoke(core.clj:5873)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 	at clojure.core$apply.invokeStatic(core.clj:659)
> 	at clojure.core$require.invokeStatic(core.clj:5911)
> 	at clojure.core$require.doInvoke(core.clj:5911)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
> 	... 32 more
> Caused by: clojure.lang.ExceptionInfo: Invariant violation in `taoensso.encore:?` [pred-form, val]:
>  [(pos-int? ttl-ms), 60000]
> `pred-form` error: java.lang.IllegalStateException: Attempting to call unbound fn: #'taoensso.encore/pos-int? {:*?data* nil, :elidable? true, :dt #inst "2016-11-19T08:26:27.047-00:00", :val 60000, :ns-str "taoensso.encore", :val-type java.lang.Long, :?err #error {
>  :cause "Attempting to call unbound fn: #'taoensso.encore/pos-int?"
>  :via
>  [{:type java.lang.IllegalStateException
>    :message "Attempting to call unbound fn: #'taoensso.encore/pos-int?"
>    :at [clojure.lang.Var$Unbound throwArity "Var.java" 43]}]
>  :trace
>  [[clojure.lang.Var$Unbound throwArity "Var.java" 43]
>   [clojure.lang.AFn invoke "AFn.java" 32]
>   [taoensso.encore$memoize_STAR_$fn__1658 invoke "encore.clj" 1630]
>   [taoensso.encore$memoize_STAR_ invokeStatic "encore.clj" 1630]
>   [taoensso.encore$memoize_STAR_ invoke "encore.clj" 1600]
>   [taoensso.timbre.appenders.core__init load nil 107]
>   [taoensso.timbre.appenders.core__init <clinit> nil -1]
>   [java.lang.Class forName0 "Class.java" -2]
>   [java.lang.Class forName "Class.java" 348]
>   [clojure.lang.RT classForName "RT.java" 2183]
>   [clojure.lang.RT classForName "RT.java" 2192]
>   [clojure.lang.RT loadClassForName "RT.java" 2211]
>   [clojure.lang.RT load "RT.java" 445]
>   [clojure.lang.RT load "RT.java" 421]
>   [clojure.core$load$fn__7846 invoke "core.clj" 6008]
>   [clojure.core$load invokeStatic "core.clj" 6007]
>   [clojure.core$load doInvoke "core.clj" 5991]
>   [clojure.lang.RestFn invoke "RestFn.java" 408]
>   [clojure.core$load_one invokeStatic "core.clj" 5812]
>   [clojure.core$load_one invoke "core.clj" 5807]
>   [clojure.core$load_lib$fn__7791 invoke "core.clj" 5852]
>   [clojure.core$load_lib invokeStatic "core.clj" 5851]
>   [clojure.core$load_lib doInvoke "core.clj" 5832]
>   [clojure.lang.RestFn applyTo "RestFn.java" 142]
>   [clojure.core$apply invokeStatic "core.clj" 659]
>   [clojure.core$load_libs invokeStatic "core.clj" 5889]
>   [clojure.core$load_libs doInvoke "core.clj" 5873]
>   [clojure.lang.RestFn applyTo "RestFn.java" 137]
>   [clojure.core$apply invokeStatic "core.clj" 659]
>   [clojure.core$require invokeStatic "core.clj" 5911]
>   [clojure.core$require doInvoke "core.clj" 5911]
>   [clojure.lang.RestFn invoke "RestFn.java" 457]
>   [taoensso.timbre$loading__5569__auto____1909 invoke "timbre.clj" 1]
>   [taoensso.timbre__init load nil 1]
>   [taoensso.timbre__init <clinit> nil -1]
>   [java.lang.Class forName0 "Class.java" -2]
>   [java.lang.Class forName "Class.java" 348]
>   [clojure.lang.RT classForName "RT.java" 2183]
>   [clojure.lang.RT classForName "RT.java" 2192]
>   [clojure.lang.RT loadClassForName "RT.java" 2211]
>   [clojure.lang.RT load "RT.java" 445]
>   [clojure.lang.RT load "RT.java" 421]
>   [clojure.core$load$fn__7846 invoke "core.clj" 6008]
>   [clojure.core$load invokeStatic "core.clj" 6007]
>   [clojure.core$load doInvoke "core.clj" 5991]
>   [clojure.lang.RestFn invoke "RestFn.java" 408]
>   [clojure.core$load_one invokeStatic "core.clj" 5812]
>   [clojure.core$load_one invoke "core.clj" 5807]
>   [clojure.core$load_lib$fn__7791 invoke "core.clj" 5852]
>   [clojure.core$load_lib invokeStatic "core.clj" 5851]
>   [clojure.core$load_lib doInvoke "core.clj" 5832]
>   [clojure.lang.RestFn applyTo "RestFn.java" 142]
>   [clojure.core$apply invokeStatic "core.clj" 659]
>   [clojure.core$load_libs invokeStatic "core.clj" 5889]
>   [clojure.core$load_libs doInvoke "core.clj" 5873]
>   [clojure.lang.RestFn applyTo "RestFn.java" 137]
>   [clojure.core$apply invokeStatic "core.clj" 659]
>   [clojure.core$require invokeStatic "core.clj" 5911]
>   [clojure.core$require doInvoke "core.clj" 5911]
>   [clojure.lang.RestFn applyTo "RestFn.java" 137]
>   [clojure.lang.Compiler$InvokeExpr eval "Compiler.java" 3652]
>   [clojure.lang.Compiler compile1 "Compiler.java" 7525]
>   [clojure.lang.Compiler compile "Compiler.java" 7592]
>   [clojure.lang.RT compile "RT.java" 408]
>   [clojure.lang.RT load "RT.java" 453]
>   [clojure.lang.RT load "RT.java" 421]
>   [clojure.core$load$fn__7846 invoke "core.clj" 6008]
>   [clojure.core$load invokeStatic "core.clj" 6007]
>   [clojure.core$load doInvoke "core.clj" 5991]
>   [clojure.lang.RestFn invoke "RestFn.java" 408]
>   [clojure.core$load_one invokeStatic "core.clj" 5812]
>   [clojure.core$compile$fn__7851 invoke "core.clj" 6018]
>   [clojure.core$compile invokeStatic "core.clj" 6018]
>   [clojure.core$compile invoke "core.clj" 6010]
>   [user$eval30$fn__39 invoke "form-init7463519023984998664.clj" 1]
>   [user$eval30 invokeStatic "form-init7463519023984998664.clj" 1]
>   [user$eval30 invoke "form-init7463519023984998664.clj" 1]
>   [clojure.lang.Compiler eval "Compiler.java" 6978]
>   [clojure.lang.Compiler eval "Compiler.java" 6968]
>   [clojure.lang.Compiler eval "Compiler.java" 6968]
>   [clojure.lang.Compiler load "Compiler.java" 7430]
>   [clojure.lang.Compiler loadFile "Compiler.java" 7368]
>   [clojure.main$load_script invokeStatic "main.clj" 277]
>   [clojure.main$init_opt invokeStatic "main.clj" 279]
>   [clojure.main$init_opt invoke "main.clj" 279]
>   [clojure.main$initialize invokeStatic "main.clj" 310]
>   [clojure.main$null_opt invokeStatic "main.clj" 344]
>   [clojure.main$null_opt invoke "main.clj" 341]
>   [clojure.main$main invokeStatic "main.clj" 423]
>   [clojure.main$main doInvoke "main.clj" 386]
>   [clojure.lang.RestFn applyTo "RestFn.java" 137]
>   [clojure.lang.Var applyTo "Var.java" 700]
>   [clojure.main main "main.java" 37]]}, :*assert* true, :?data nil, :?line nil, :form-str "(pos-int? ttl-ms)"}
> 	at clojure.core$ex_info.invokeStatic(core.clj:4725)
> 	at clojure.core$ex_info.invoke(core.clj:4725)
> 	at taoensso.truss.impl$_invar_violation_BANG_.invokeStatic(impl.clj:151)
> 	at taoensso.truss.impl$_invar_violation_BANG_.invoke(impl.clj:122)
> 	at taoensso.encore$memoize_STAR_$fn__1658.invoke(encore.clj:1630)
> 	at taoensso.encore$memoize_STAR_.invokeStatic(encore.clj:1630)
> 	at taoensso.encore$memoize_STAR_.invoke(encore.clj:1600)
> 	at taoensso.timbre.appenders.core__init.load(Unknown Source)
> 	at taoensso.timbre.appenders.core__init.<clinit>(Unknown Source)
> 	... 86 more
> Compilation failed: Subprocess failed
> 
> 
>

**Comment by vadali** [comment]
Just realized this is related to the issue 29 [here](https://github.com/ptaoussanis/encore/issues/29#issuecomment-239042741)

My encore version is `[com.taoensso/encore "2.87.0"]`. Any clues? This is really frustrating..

Also, on clojure 1.9 `lein clean` does not seem to help as mentioned in the first comment..

**Comment by vadali** [comment]
oh my... what a mess.. ok, so I finally figured it out.. one of my other projects used an old timbre version, and even though I included an `:exclusions [com.taoensso/encore com.taoensso/timbre]` on that entry (and globally too!), it was still brought in! Sounds like a feature of leiningen.. 

In any case, I fixed the dependencies on that other project and it now seems to work fine..

pheww that was exhausting! 

Sorry for the spam :face_with_head_bandage:

**Comment by ptaoussanis** [comment]
No problem at all, we've all been hit by dependency nonsense before :-)

Happy you managed to sort it out!

Cheers :-)
