### ISSUE TITLE
java.lang.IllegalAccessError: reader-error does not exist - when used with Cloverage

### ISSUE THREAD

**Issue by anujsrc** [ptaoussanis/timbre#263]
Timbre fails when used in conjunction with [Cloverage](https://github.com/cloverage/cloverage) with the following error-

```
% lein with-profiles +test cloverage                                                                                                                      18-07-02 - 0:33:43
WARNING: reader-conditional already refers to: #'clojure.core/reader-conditional in namespace: clojure.tools.reader.impl.utils, being replaced by: #'clojure.tools.reader.impl.utils/reader-conditional
WARNING: tagged-literal already refers to: #'clojure.core/tagged-literal in namespace: clojure.tools.reader.impl.utils, being replaced by: #'clojure.tools.reader.impl.utils/tagged-literal
Loading namespaces:  (timbre-cloverage.core)
Test namespaces:  (timbre-cloverage.core-test)
Exception in thread "main" java.lang.Exception: Couldn't eval form (cloverage.instrument/wrapm cloverage.coverage/track-coverage 1 ^{:line 1, :column 1, :end-line 2, :end-column 43, :file "timbre_cloverage/core.clj"} (^{:line 1, :column 2, :end-line 1, :end-column 4} ns ^{:line 1, :column 5, :end-line 1, :end-column 26} timbre-cloverage.core ^{:line 2, :column 3, :end-line 2, :end-column 42} (:require ^{:line 2, :column 13, :end-line 2, :end-column 41} [^{:line 2, :column 14, :end-line 2, :end-column 29} taoensso.timbre :as ^{:line 2, :column 34, :end-line 2, :end-column 40} timbre])))
(do (cloverage.coverage/cover 1) (do (clojure.core/in-ns (quote timbre-cloverage.core)) (. (. clojure.lang.Namespace find (quote timbre-cloverage.core)) resetMeta {:line 1, :column 5, :end-line 1, :end-column 26}) ((fn* loading__6434__auto__ ([] (. clojure.lang.Var (clojure.core/pushThreadBindings #:clojure.lang.Compiler{LOADER (. (. loading__6434__auto__ getClass) getClassLoader)})) (try (clojure.core/refer (quote clojure.core)) (clojure.core/require (quote [taoensso.timbre :as timbre])) (finally (. clojure.lang.Var (clojure.core/popThreadBindings))))))) (if (. (quote timbre-cloverage.core) equals (quote clojure.core)) nil (do (. clojure.lang.LockingTransaction (clojure.core/runInTransaction (fn* ([] (clojure.core/commute (clojure.core/deref (var clojure.core/*loaded-libs*)) clojure.core/conj (quote timbre-cloverage.core)))))) nil))))
(ns timbre-cloverage.core (:require [taoensso.timbre :as timbre]))
, compiling:(/tmp/form-init5044471838593707424.clj:1:73)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.Compiler.loadFile(Compiler.java:7452)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$init_opt.invokeStatic(main.clj:280)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invokeStatic(main.clj:311)
        at clojure.main$null_opt.invokeStatic(main.clj:345)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Couldn't eval form (cloverage.instrument/wrapm cloverage.coverage/track-coverage 1 ^{:line 1, :column 1, :end-line 2, :end-column 43, :file "timbre_cloverage/core.clj"} (^{:line 1, :column 2, :end-line 1, :end-column 4} ns ^{:line 1, :column 5, :end-line 1, :end-column 26} timbre-cloverage.core ^{:line 2, :column 3, :end-line 2, :end-column 42} (:require ^{:line 2, :column 13, :end-line 2, :end-column 41} [^{:line 2, :column 14, :end-line 2, :end-column 29} taoensso.timbre :as ^{:line 2, :column 34, :end-line 2, :end-column 40} timbre])))
(do (cloverage.coverage/cover 1) (do (clojure.core/in-ns (quote timbre-cloverage.core)) (. (. clojure.lang.Namespace find (quote timbre-cloverage.core)) resetMeta {:line 1, :column 5, :end-line 1, :end-column 26}) ((fn* loading__6434__auto__ ([] (. clojure.lang.Var (clojure.core/pushThreadBindings #:clojure.lang.Compiler{LOADER (. (. loading__6434__auto__ getClass) getClassLoader)})) (try (clojure.core/refer (quote clojure.core)) (clojure.core/require (quote [taoensso.timbre :as timbre])) (finally (. clojure.lang.Var (clojure.core/popThreadBindings))))))) (if (. (quote timbre-cloverage.core) equals (quote clojure.core)) nil (do (. clojure.lang.LockingTransaction (clojure.core/runInTransaction (fn* ([] (clojure.core/commute (clojure.core/deref (var clojure.core/*loaded-libs*)) clojure.core/conj (quote timbre-cloverage.core)))))) nil))))
(ns timbre-cloverage.core (:require [taoensso.timbre :as timbre]))

        at cloverage.instrument$instrument$fn__1782.invoke(instrument.clj:444)
        at cloverage.instrument$instrument.invokeStatic(instrument.clj:436)
        at cloverage.instrument$instrument.invoke(instrument.clj:415)
        at cloverage.coverage$run_main$fn__2884.invoke(coverage.clj:202)
        at cloverage.coverage$run_main.invokeStatic(coverage.clj:199)
        at cloverage.coverage$run_main.invoke(coverage.clj:158)
        at cloverage.coverage$_main.invokeStatic(coverage.clj:256)
        at cloverage.coverage$_main.doInvoke(coverage.clj:251)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at clojure.lang.Var.invoke(Var.java:390)
        at user$eval149.invokeStatic(form-init5044471838593707424.clj:1)
        at user$eval149.invoke(form-init5044471838593707424.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7052)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        ... 12 more
Caused by: java.lang.IllegalAccessError: reader-error does not exist, compiling:(clojure/tools/reader/edn.clj:1:1)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.RT.loadResourceScript(RT.java:379)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.load(RT.java:460)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$load_one.invoke(core.clj:5843)
        at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
        at clojure.core$load_lib.invokeStatic(core.clj:5887)
        at clojure.core$load_lib.doInvoke(core.clj:5868)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5925)
        at clojure.core$load_libs.doInvoke(core.clj:5909)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5947)
        at clojure.core$require.doInvoke(core.clj:5947)
        at clojure.lang.RestFn.invoke(RestFn.java:551)
        at taoensso.encore$eval3321$loading__6434__auto____3322.invoke(encore.clj:1)
        at taoensso.encore$eval3321.invokeStatic(encore.clj:1)
        at taoensso.encore$eval3321.invoke(encore.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7051)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        at clojure.lang.RT.loadResourceScript(RT.java:379)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.load(RT.java:460)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$load_one.invoke(core.clj:5843)
        at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
        at clojure.core$load_lib.invokeStatic(core.clj:5887)
        at clojure.core$load_lib.doInvoke(core.clj:5868)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5925)
        at clojure.core$load_libs.doInvoke(core.clj:5909)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5947)
        at clojure.core$require.doInvoke(core.clj:5947)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at taoensso.timbre$eval2908$loading__6434__auto____2909.invoke(timbre.clj:1)
        at taoensso.timbre$eval2908.invokeStatic(timbre.clj:1)
        at taoensso.timbre$eval2908.invoke(timbre.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7051)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        at clojure.lang.RT.loadResourceScript(RT.java:379)
        at clojure.lang.RT.loadResourceScript(RT.java:370)
        at clojure.lang.RT.load(RT.java:460)
        at clojure.lang.RT.load(RT.java:426)
        at clojure.core$load$fn__6548.invoke(core.clj:6046)
        at clojure.core$load.invokeStatic(core.clj:6045)
        at clojure.core$load.doInvoke(core.clj:6029)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5848)
        at clojure.core$load_one.invoke(core.clj:5843)
        at clojure.core$load_lib$fn__6493.invoke(core.clj:5888)
        at clojure.core$load_lib.invokeStatic(core.clj:5887)
        at clojure.core$load_lib.doInvoke(core.clj:5868)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5925)
        at clojure.core$load_libs.doInvoke(core.clj:5909)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5947)
        at clojure.core$require.doInvoke(core.clj:5947)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at timbre_cloverage.core$eval2900$loading__6434__auto____2901.invoke(timbre_cloverage/core.clj:1)
        at timbre_cloverage.core$eval2900.invokeStatic(timbre_cloverage/core.clj:1)
        at timbre_cloverage.core$eval2900.invoke(timbre_cloverage/core.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7051)
        at clojure.lang.Compiler.eval(Compiler.java:7052)
        at clojure.lang.Compiler.eval(Compiler.java:7025)
        at clojure.core$eval.invokeStatic(core.clj:3206)
        at clojure.core$eval.invoke(core.clj:3202)
        at cloverage.instrument$instrument$fn__1782$fn__1783.invoke(instrument.clj:439)
        at cloverage.instrument$instrument$fn__1782.invoke(instrument.clj:437)
        ... 26 more
Caused by: java.lang.IllegalAccessError: reader-error does not exist
        at clojure.core$refer.invokeStatic(core.clj:4215)
        at clojure.core$refer.doInvoke(core.clj:4183)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_lib.invokeStatic(core.clj:5906)
        at clojure.core$load_lib.doInvoke(core.clj:5868)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5925)
        at clojure.core$load_libs.doInvoke(core.clj:5909)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5947)
        at clojure.core$require.doInvoke(core.clj:5947)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at clojure.tools.reader.edn$eval3329$loading__6434__auto____3330.invoke(edn.clj:9)
        at clojure.tools.reader.edn$eval3329.invokeStatic(edn.clj:9)
        at clojure.tools.reader.edn$eval3329.invoke(edn.clj:9)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7051)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        ... 115 more
Error encountered performing task 'cloverage' with profile(s): 'base,system,user,provided,dev,test'
Suppressed exit
```
Here is my ``project.clj`` file-

```
(defproject timbre_cloverage "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/tools.reader "0.10.0"]
                 [org.clojure/tools.nrepl "0.2.12"]
                 [com.taoensso/timbre "4.8.0"]]
  :plugins [[:lein-cloverage "1.0.9"]]
  :profiles {:provided {:dependencies [[org.clojure/tools.reader "0.10.0"]
                                       [org.clojure/tools.nrepl "0.2.12"]]}
             :uberjar {:aot :all :omit-source true}})
```
``core.clj`` just requires timbre namespace-

```
(ns timbre-cloverage.core
  (:require [taoensso.timbre :as timbre]))

(defn foo
  "I don't do a whole lot."
  [x]
  (println x "Hello, World!"))
```
``lein test`` works fine without any issues-

```
% lein with-profiles +test test                                                                                                                           18-07-02 - 0:34:14

lein test timbre-cloverage.core-test

lein test :only timbre-cloverage.core-test/a-test

FAIL in (a-test) (core_test.clj:7)
FIXME, I fail.
expected: (= 0 1)
  actual: (not (= 0 1))

Ran 1 tests containing 1 assertions.
1 failures, 0 errors.
Tests failed.
Error encountered performing task 'test' with profile(s): 'base,system,user,provided,dev,test'
Tests failed.
```
I have debugged further and found that it eventually boils down to the usage of ``tools.reader`` that is ``1.x.x`` in Cloverage and also in latest ``encore``. [But ``timbre`` release still uses older version of ``encore`` that still relies on ``0.x.x`` version of ``tools.reader``](https://github.com/ptaoussanis/encore/blob/c03938239f50cb1baa5ff2770b952fb93e358ef6/project.clj). That might be an issue.

**Comment by anujsrc** [comment]
If I enforce ``tools.reader`` to be ``1.2.2``, it works fine-

```
(defproject timbre_cloverage "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/tools.reader "1.2.2"]
                 [org.clojure/tools.nrepl "0.2.12"]
                 [com.taoensso/timbre "4.8.0"]]
  :plugins [[:lein-cloverage "1.0.9"]]
  :profiles {:uberjar {:aot :all :omit-source true}})
```

**Comment by hlolli** [comment]
Got the same error, wouldn't have closed it, this needs to be fixed. 

But thanks for posting a temp fix.

**Comment by anujsrc** [comment]
@hlolli - Just reopened for @ptaoussanis to comment.

**Comment by ptaoussanis** [comment]
Hi there,

This looks like a dependency conflict. Should be resolved with the next release, which'll update dependencies. In the meantime, @anujsrc's solution looks good. (Thanks Anuj!).

**Comment by superwesman** [comment]
I see these same symptoms with timbre 4.10.0, lein-cloverage 1.1.1

**Comment by jumarko** [comment]
@ptaoussanis Has this been resolved? How about the new release? ;)

**Comment by ptaoussanis** [comment]
Deps updated in new release, closing
