### ISSUE TITLE
var: #'taoensso.timbre/level>= is not public

### ISSUE THREAD

**Issue by pieterbreed** [ptaoussanis/timbre#321]
## upgrade to latest causes problems via another dependency

I have [timbre-ns-pattern-level](https://github.com/yonatane/timbre-ns-pattern-level) as a dependency of my project. When I updated to most-recent versions of `timbre` (& `encore`), I started receiving an exception while compiling by project, via the dependency on `timbre-ns-pattern-level`.

[This github ticket in timbre-ns-pattern-level is logged on their side too...](https://github.com/yonatane/timbre-ns-pattern-level/issues/3). I'm logging the issue on both boards, because maybe it's easy to make the var public again (?).

## versions in question

```clj
                 ;; these dependency versions cause timbre-ns-pattern-level to break during compile
                 ;; see https://github.com/yonatane/timbre-ns-pattern-level/issues/3
                 ;; [com.taoensso/encore "3.3.0"]
                 ;; [com.taoensso/timbre "5.0.1"]

                 [com.taoensso/encore "3.0.0" :upgrade false]
                 [com.taoensso/timbre "4.10.0" :upgrade false]
```

## Original exception

```
Exception in thread "main" Syntax error compiling taoensso.timbre/level>= at (timbre_ns_pattern_level.clj:19:18).
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7115)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7095)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
	at clojure.lang.Compiler.analyze(Compiler.java:6745)
	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2829)
...
	at clojure.lang.RT.doInit(RT.java:486)
	at clojure.lang.RT.init(RT.java:467)
	at clojure.main.main(main.java:38)
Caused by: java.lang.IllegalStateException: var: #'taoensso.timbre/level>= is not public
	at clojure.lang.Compiler.isInline(Compiler.java:6922)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7100)
	... 205 more
Compilation failed: Subprocess failed (exit code: 1)
```

**Comment by ptaoussanis** [comment]
@pieterbreed Hi Pieter, thanks for the report!

I'm open to making `level>=` public as an implementation detail - but would advise updating to Timbre 5's [own namespace filtering](http://ptaoussanis.github.io/timbre/taoensso.timbre.html#var-*config*) long-term if possible.

**Comment by ptaoussanis** [comment]
Will try cut a new release this weekend 👍

**Comment by ptaoussanis** [comment]
`[com.taoensso/timbre "5.1.0"]` on Clojars now 👍
